// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_omtFBhCGRIUMuq9lOw51mraQp09LjII',
    appId: '1:677476469510:web:580d4f62f505c69814ec87',
    messagingSenderId: '677476469510',
    projectId: 'salewang-f26de',
    authDomain: 'salewang-f26de.firebaseapp.com',
    databaseURL: 'https://salewang-f26de-default-rtdb.firebaseio.com',
    storageBucket: 'salewang-f26de.firebasestorage.app',
    measurementId: 'G-6HHR8NZCGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXuAslqbs0n-oWZ9dTCkmeVjRLUcdEo4',
    appId: '1:677476469510:android:cc9f041613ef832314ec87',
    messagingSenderId: '677476469510',
    projectId: 'salewang-f26de',
    databaseURL: 'https://salewang-f26de-default-rtdb.firebaseio.com',
    storageBucket: 'salewang-f26de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFdEmWI2ENPHJ0jGf0grdMlj39B8pC7g',
    appId: '1:677476469510:ios:f300b16f887e636014ec87',
    messagingSenderId: '677476469510',
    projectId: 'salewang-f26de',
    databaseURL: 'https://salewang-f26de-default-rtdb.firebaseio.com',
    storageBucket: 'salewang-f26de.firebasestorage.app',
    iosBundleId: 'com.example.salewang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFdEmWI2ENPHJ0jGf0grdMlj39B8pC7g',
    appId: '1:677476469510:ios:f300b16f887e636014ec87',
    messagingSenderId: '677476469510',
    projectId: 'salewang-f26de',
    databaseURL: 'https://salewang-f26de-default-rtdb.firebaseio.com',
    storageBucket: 'salewang-f26de.firebasestorage.app',
    iosBundleId: 'com.example.salewang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_omtFBhCGRIUMuq9lOw51mraQp09LjII',
    appId: '1:677476469510:web:f09c9255c6f40c7f14ec87',
    messagingSenderId: '677476469510',
    projectId: 'salewang-f26de',
    authDomain: 'salewang-f26de.firebaseapp.com',
    databaseURL: 'https://salewang-f26de-default-rtdb.firebaseio.com',
    storageBucket: 'salewang-f26de.firebasestorage.app',
    measurementId: 'G-VG1X809PLM',
  );

}